name: Build and Deploy
on:
  push:
    paths: ['src/components/**'] # Trigger the action only when files change in the folders defined here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          yarn install
          yarn run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: storybook # The branch the action should deploy to.
          folder: storybook-static # The folder that the build-storybook script generates files.
